IDEAL_PITCH_ANSWER = {
    "0": "Health insurance policy lena zaroori hai kyunki: 1. Health insurance policy aapki aur aapke pariwar ke swasthya ki suraksha karti hai. Aapko financial protection deti hai jab aapko medical emergency, bimaar hona ya chikitsa ki zaroorat hoti hai. 2. Aapki health insurance policy aapko acche hospitals aur doctors ke access provide karti hai, jisse aap acha quality healthcare receive kar sakte hain. 3. Agar aapke paas health insurance policy hai, toh aapko expensive medical treatments ke liye khud ka paisa kharch karne ki zaroorat nahi hoti hai. Insurance company aapke liye us expense ka bhugtan karti hai. 4. Health insurance policy aapki financial burden ko kam karti hai aur aapki savings aur investments ko protect karti hai. 5. Aapki policy aapko regular health check-ups aur preventive care services jaise vaccinations aur screenings ke liye bhi cover karti hai, jisse aap bimariyon se bach sakte hain.",
    "1": "Health insurance policy mein saal bhar tak cover amount ki limit policy ke terms and conditions par depend karti hai. Aam taur par, cover amount 1 crore tak ho sakti hai, lekin kuch companies higher limits bhi offer karti hai. Aapki policy type, age, health condition aur anya factors, cover amount par asar dalte hain. Aap apni needs aur budget ke hisab se ek cover amount choose kar sakte hain jo aapko sufficient financial protection provide kare.",
    "2":  f"Health insurance generally 80% se 100% tak ka coverage kar sakta hai hospitalization expenses ka. Yeh percentage policy terms and conditions aur policy type par depend karta hai. Kuch policies mein aapko ek fixed percentage jaise 80% coverage milega, jabki dusri policies mein aap puri expenses ka 100% reimbursement bhi pa sakte hain. Aapko bhi apni policy ke details ko carefully check karna chahiye taaki aapko hospitalization expenses ke liye sufficient financial protection mile.",
    "3": "Haan, health insurance accident-related hospitalization expenses ko cover karta hai. Agar aapki policy mein accident coverage included hai, toh aap eligible ho jayenge accident se hone wale chot, fractures, surgeries, aur anya treatment expenses ke liye claim karne ke liye. Iske alawa, aapko room charges, ICU charges, doctor fees, medicines, diagnostic tests, aur ambulance charges bhi cover ho sakte hain. Accident-related hospitalization expenses ka cover aapki policy terms and conditions par depend karta hai, isliye policy documents ko thorough padhna zaruri hai aur jaruri details ko clarify karne ke liye insurance provider se baat karna chahiye.",
    "4": "Seasonal illnesses jaise COVID, fever, malaria, dengue, pneumonia, malaria se related hospital treatment aksar health insurance policy mein cover hota hai, lekin coverage ka start time policy to policy alag ho sakta hai. Generally, policy purchase ke 30 dino ke baad hospital treatment coverage shuru ho jati hai. Isliye samay rehte apne policy ki terms and conditions ko padhkar ya apne insurance provider se confirm karke check karna chahiye ki aapke policy mein kon kon se seasonal illnesses ka coverage hai aur coverage kab se shuru hota hai. Coverage shuru hone se pehle, aap treatment cost ko apne pocket se bear karna pad sakta hai.",
    "5": "Agar aapke pehle se koi pre-existing disease nahi hai aur achanak serious bimari ho jaati hai jaise dil ka rog, lungs ka rog, liver ka rog, kidney ka rog, diabetes, blood pressure, toh aapki health insurance policy normally usse cover karegi. Yeh bimari aapki policy terms and conditions par depend karegi, jaise waiting period, exclusions aur pre-existing disease coverage. Lekin, dhyan dena zaruri hai ki kuch policies mein waiting period hota hai jismein aapki policy ke shuruaati mahino mein certain bimariyon ke liye claim nahi ho sakta hai. Isliye, health insurance policy lena ho toh pre-existing diseases coverage ke saath rahiye taaki aapko aise bimariyon se jude future expenses ka protection mile."
}

CLIENT_QUESTION = {
    "0": "Hi, mene apka miss call dekha isliye call kiya. Kya me jan sakta hu, ap kon hai?",
    "1": "Ohk... vese health insurance lena ke bareme soch to raha hu. Online bohot sari policies dekhi, par me confuse ho gaya hu. Vo kya hai na mujhe apni wife aur 2 baccho ke liye bhi health plan chahiye. Lekin sabke liye health plan lena kafi mehnga pad jayega na?",
    "2": "Dekhiye wo sab to theek hai, leking mujhe ek doubt hai. Dekhiye agar me Rs. 10 lakh ke sum insured wala family floater plan leta hu, to kya mere family ke har member ko 10 lakh tak ka coverage milega. Ya pure 10 lakh ke coverage ko 4 hisso me batkar har kisiko 2.5 lakhs ka coverage diya jaega?",
    "3": "Oh...thik hai. Par agar kisi saal humne jyada claims kiye aur sum insured khatam ho gaya to? Aage ke claims nahi milenge?",
    "4": "Accha...thik hai fir ap bol rahe hai vesi koi family floater policy hi le leta hu. Ap kuch policies bhej dijiye hum decide kar lete hai fir."
}
